### ISSUE TITLE
Aluminium profiles joints

### ISSUE THREAD

**Issue by marcgenevat** [CanyoneroRobotics/TFM#16]
All the needed joints have already been designed with PTC Creo and now we're 3D printing prototypes to test them with the profiles.

The first test was pretty good. We had to make the holes bigger with a drill due to the 3d printer tolerances. Besides, we're thinking to add some flanges in order to avoid rotations atthe profiles so we have a very strong and robust chassis.

![img-20160704-wa0019 jpg](https://cloud.githubusercontent.com/assets/15161499/16603568/5543ed5e-431d-11e6-913e-25b12fe86934.jpeg)

During this week we'll 3d print the new prototypes with the changes we've mentioned. Once we have these final designs, we'll be able to start cutting the profiles and building the chassis, at least the first and second floors, which would be the skeleton of the robot.

**Comment by carlosjoserg** [comment]
:+1:
