### ISSUE TITLE
Raspberry Pi 3 ROS Indigo installation and basic configuration

### ISSUE THREAD

**Issue by simium** [CanyoneroRobotics/TFM#2]
Follow: http://wiki.ros.org/jade/Installation/UbuntuARM

**Comment by marcgenevat** [comment]
Daleeee Juampe, que ja ho tens tot!

**Comment by simium** [comment]
Finally I've chosen Indigo over Jade because of its stability and the availability of packages for Raspbian.

See: http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Indigo%20on%20Raspberry%20Pi
